# Generated by Django 2.0.9 on 2018-11-16 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Division'),
        ),
    ]
