# Generated by Django 2.0.9 on 2018-11-16 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20181116_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='app_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
