# Generated by Django 2.0.9 on 2018-11-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_division_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='search_form',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
